# Generated by Django 6.0.3 on 2026-03-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='attended',
            field=models.BooleanField(default=False),
        ),
    ]
